# user_default: null
user_name: '{{ user_default | default("user") }}'
# user_password: ""
user_group: '{{ user_name }}'
user_groups:
  - adm
  - wheel
  - sudo
  - users
user_shell: /bin/bash
# user_home: '/home/{{ user_name }}'
# user_comment: ""
user_sudo_without_password: '{{ wsl_setup.require_password | default(false) | ternary(false, true) }}'
