- name: Add docker gpg 
  become: true
  ansible.builtin.command:
    argv:
      - curl
      - -fsSL
      - https://download.docker.com/linux/ubuntu/gpg
      - -o
      - '{{ apt_keyrings_dir }}/docker.asc'
    creates: '{{ apt_keyrings_dir }}/docker.asc'
  environment: '{{ proxy_env }}'

- name: Add docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb
      [arch={{ apt_architecture}}
      signed-by={{ apt_keyrings_dir }}/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ apt_release }}
      stable
    filename: docker
    state: present

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
