# TODO: dnfは未対応

- name: Fail without apt
  ansible.builtin.fail:
    msg: support apt only
  when: ansible_pkg_mgr != "apt"

- name: Add docker gpg 
  become: true
  ansible.builtin.command:
    argv:
      - curl
      - -fsSL
      - https://download.docker.com/linux/ubuntu/gpg
      - -o
      - '{{ apt_keyrings_dir }}/docker.asc'
    creates: '{{ apt_keyrings_dir }}/docker.asc'
  environment: '{{ proxy_env }}'

- name: Add docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb
      [arch={{ apt_architecture}}
      signed-by={{ apt_keyrings_dir }}/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ apt_release }}
      stable
    filename: docker
    state: present

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add default user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ user_default_user.name }}'
    groups: docker
    append: true

- name: Make dockre.service.d diretory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: proxy_env

- name: Copy template proxy config for docker service
  become: true
  ansible.builtin.template:
    src: docker.service.d/docker_proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker_proxy.conf
    owner: root
    group: root
    mode: '0644'
  when: proxy_env
