- name: Install language package by apt
  become: true
  ansible.builtin.apt:
    name: 'language-pack-{{ lang_package }}'
  when: ansible_pkg_mgr == "apt"

- name: Install language package by dnf
  become: true
  ansible.builtin.dnf:
    name: 'language-pack-{{ lang_package }}'
  when: ansible_pkg_mgr == "dnf"

- name: Create locale
  become: true
  community.general.locale_gen:
    name: '{{ lang_locale }}'

- name: Check localectl status
  ansible.builtin.command:
    cmd: localectl status
  changed_when: false
  register: lang_run_localectl_status
  when: wsl_systemd

- name: Run localectl set-locale
  become: true
  ansible.builtin.command:
    cmd: 'localectl set-locale {{ lang_locale }}'
  changed_when: true
  when:
    - wsl_systemd
    - >-
      lang_run_localectl_status.stdout_lines | first
        is not search("LANG=" ~ lang_locale)

# FIXME: dnfは日本語manが無い？
- name: Install manual packages
  become: true
  ansible.builtin.apt:
    name:
      - 'manpages-{{ lang_package }}'
      - 'manpages-{{ lang_package }}-dev'
  when: ansible_pkg_mgr == "apt"
