- name: Install python psycopg2 for ansible
  become: true
  ansible.builtin.package:
    state: present
    name: python3-psycopg2

- name: Create default user as superuser
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_unix_socket: /run/postgresql
    login_user: postgres
    state: present
    name: '{{ user_default_user.name }}'
    role_attr_flags: SUPERUSER

- name: Create database for default user as superuser
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    login_unix_socket: /run/postgresql
    login_user: postgres
    state: present
    name: '{{ user_default_user.name }}'
