- name: Install packages by apt
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    install_recommends: '{{ item not in app_no_install_recommends }}'
  loop: '{{ app_list }}'
  when: ansible_pkg_mgr == "apt"

- name: Install packages by dnf
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    install_weak_deps: '{{ item not in app_no_install_recommends }}'
  loop: '{{ app_list }}'
  when: ansible_pkg_mgr == "apt"

- name: Select editor
  become: true
  community.general.alternatives:
    name: '{{ item.key }}'
    path: '{{ item.value }}'
  loop: '{{ app_alternatives | dict2items }}'
