- name: Run where in windows
  ansible.builtin.shell:
    cmd: '{{ win_system_bin }}/where.exe {{ win_where_name }} 2>/dev/null'
  changed_when: false
  ignore_errors: true
  register: win_run_where

- name: Task win_path in wsl
  ansible.builtin.include_role:
    name: wsl
    tasks_from: wsl_path
  vars:
    wsl_win_path: '{{ win_run_where.stdout_lines | first }}'
  when: win_run_where.rc == 0

- name: Setting win_where_path
  ansible.builtin.set_fact:
    win_where_path: '{{ (win_run_where.rc == 0) | ternary(wsl_wsl_path, "") }}'
