- name: Get all groups
  ansible.builtin.getent:
    database: group
  when: ansible_facts.getent_group is not defined

- name: Filter user_groups
  ansible.builtin.set_fact:
    user_groups: >-
      {{ ansible_facts.getent_group | dict2items | map(attribute='key') | list
        | intersect(user_groups) }}

- name: Add default group
  become: true
  ansible.builtin.group:
    name: '{{ user_group }}'
  register: user_default_group

- name: Add default user
  become: true
  ansible.builtin.user:
    name: '{{ user_name }}'
    password: '{{ user_password | default(omit) }}'
    group: '{{ user_group }}'
    groups: '{{ user_groups }}'
    shell: '{{ user_shell | default(omit) }}'
    home: '{{ user_home | default(omit) }}'
    comment: '{{ user_comment | default(omit) }}'
    update_password: on_create
  register: user_default_user
