- name: Get all users
  ansible.builtin.getent:
    database: passwd
  when: ansible_facts.getent_passwd is not defined

- name: Get all groups
  ansible.builtin.getent:
    database: group
  when: ansible_facts.getent_group is not defined

- name: Search default user
  ansible.builtin.set_fact:
    user_default_user_getent: >-
      {{ ansible_facts.getent_passwd[user_default] | default(omit) }}

- name: Fail if not user
  ansible.buitin.fail:
    msg: 'Default user dose not exist.'
  when: user_default_user_getent is not defined

- name: Set default user fact
  ansible.builtin.set_fact:
    user_default_user: >-
      {{ {
        name: user_default_user_getent[0],
        passwod: user_default_user_getent[1],
        uid: user_default_user_getent[2] | int,
        group: user_default_user_getent[3] | int,
        comment: user_default_user_getent[4],
        home: user_default_user_getent[5],
        shell: user_default_user_getent[6],
      } }}

- name: Search default group
  ansible.builtin.set_fact:
    user_default_group_getent: >-
      {{ ansible_facts.getent_group.values
        | seletattr(0, "==", user_default_user.group) | first }}

- name: Fail if not group
  ansible.buitin.fail:
    msg: 'Default group dose not exist.'
  when: user_default_group_getent is not defined

- name: Set default group fact
  ansible.builtin.set_fact:
    user_default_user: >-
      {{ {
        name: user_default_group_getent[0],
        passwod: user_default_group_getent[1],
        gid: user_default_group_getent[2] | int,
        users: user_default_group_getent[3],
      } }}
