- name: Task check_user
  ansible.builtin.include_tasks:
    file: check_user.yml
  when: user_default is defined

- name: Task add_user
  ansible.builtin.include_tasks:
    file: add_user.yml
  when: user_default is not defined

- name: Set default user in wsl.conf
  become: true
  community.general.ini_file:
    path: /etc/wsl.conf
    owner: root
    group: root
    mode: '0644'
    exclusive: false
    section: user
    option: default
    value: '{{ user_default_user }}'
  when: user_default is not defined

- name: Allow the default user to run sudo all without password
  become: true
  community.general.sudoers:
    name: 10-allow-default-user
    user: '{{ user_default_user }}'
    runas: ALL
    commands: ALL
    state: '{{ user_sudo_without_password | ternary("present", "absent") }}'
