- name: Make apt_keyrings_dir
  become: true
  ansible.builtin.file:
    path: '{{ apt_keyrings_dir }}'
    state: directory
    mode: '0755'
    
- name: Run dpkg --print-architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  changed_when: false
  register: apt_run_dpkg_print_architecture

- name: Set apt_architecture
  ansible.builtin.set_fact:
    apt_architecture: apt_run_dpkg_print_architecture.stdout

- name: Set apt_release
  ansible.builtin.set_fact:
    apt_architecture: '{{ ansible_distribution_release }}'
