- name: Make diretory
  become: true
  ansible.builtin.file:
    path: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop: '{{ system_proxy_etc_files | map("dirname") }}'

- name: Copy template config to etc directory for proxy
  become: true
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ system_proxy_etc_files }}'

- name: Copy proxy setting for apt
  ansible.builtin.template:
    src: 'apt/apt.conf.d/90curtin-aptproxy.j2'
    dest: '/etc/apt/apt.conf.d/90curtin-aptproxy'
    owner: root
    group: root
    mode: '0644'
  when: ansible_pkg_mgr == "apt"

- name: Insert timeout in dnf.conf for dnf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^timeout=.*$'
    line: 'timeout=600'
  when: ansible_pkg_mgr == "dnf"

- name: Insert proxy in dnf.conf for dnf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^proxy=.*$'
    line: 'proxy={{ proxy_env.http_proxy }}'
  when: ansible_pkg_mgr == "dnf"
